posts:
  resource: RestBundle\Controller\PostController
  type: rest
  prefix: /v1
  name_prefix: api_1_

comentarios:
  resource: RestBundle\Controller\ComentarioController
  type: rest
  prefix: /v1
  name_prefix: api_1_
